name: Question
about: Ask a question
labels: ["question"]

body:
  - type: textarea
    id: question
    attributes:
      label: Question
      placeholder: Ask your question here.
    validations:
      required: true